Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Ans:
list_ variable is a list whereas, array_list variable is a numpy array.

In [3]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [5]:
print("list_:")
for i in list_:
    print(f"The data type of {i} is {type(i)}")

print("array_list:")
for i in array_list:
    print(f"The data type of {i} is {type(i)}")


list_:
The data type of 1 is <class 'str'>
The data type of 2 is <class 'str'>
The data type of 3 is <class 'str'>
The data type of 4 is <class 'str'>
The data type of 5 is <class 'str'>
array_list:
The data type of 1 is <class 'numpy.str_'>
The data type of 2 is <class 'numpy.str_'>
The data type of 3 is <class 'numpy.str_'>
The data type of 4 is <class 'numpy.str_'>
The data type of 5 is <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list: 
Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [6]:
array_list = np.array(object = list_,dtype = int)


In [7]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Hence, we can see the data has been converted from string to integer in numpy array.

Consider the below code to answer further questions:

In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [9]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [13]:
mat = np.zeros((3,3),dtype = int)

In [14]:
mat

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [18]:
identity = np.zeros((5,5),dtype = int)
for i in range(len(identity)):
    for j in range(len(identity[0])):
        if(i==j):
            identity[i][j]=1
print(identity)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
